blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/tommcfarlin/code-standard-selector/discussions
    about: Please ask and answer questions here.